# Generated by Django 5.1.4 on 2025-01-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonnesAffaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vente.produit')),
            ],
        ),
    ]
