# Generated by Django 5.1.4 on 2025-01-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0009_pub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BonnesAffaires',
            new_name='BonnesAffaire',
        ),
    ]
