# Generated by Django 5.1.4 on 2025-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0010_rename_bonnesaffaires_bonnesaffaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='addresse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='ville',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
