# Generated by Django 5.1.4 on 2025-02-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0011_commande_addresse_commande_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='image',
        ),
    ]
