# Generated by Django 5.1.4 on 2025-03-06 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0012_remove_pub_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='addresse',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='user',
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.TextField(default='Adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='nom',
            field=models.CharField(default='Default nom', max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='prenom',
            field=models.CharField(default='Default Address', max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(default='Default telephone', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='ville',
            field=models.CharField(default='Default ville', max_length=100),
        ),
    ]
